[platformio]
default_envs = esp32dev
core_dir = pio-core
src_dir = src
include_dir = include
lib_dir = lib
data_dir = data
test_dir = test

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_port = COM4
monitor_port = COM4

build_flags =
  -D FW_NAME=\"PM1611_RS485_READER\"
  -D FW_VERSION=\"0.1.0-dev\"

lib_deps =
  knolleary/PubSubClient @ ^2.8
  olikraus/U8g2 @ ^2.35.30
  arduino-libraries/Ethernet @ ^2.0.0
