[platformio]
default_envs = esp32dev
core_dir = pio-core

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_port = COM4
monitor_port = COM4
build_flags =
  -D FW_VERSION=\"0.1.0\"
